### PR TITLE
Fix dataset close call

### PR DESCRIPTION
**Pull request by erikh**
The closing of the children after the call to dataset_list_close causes
a detected double-free in the library. This code was removed.

I checked that the program was not leaking memory, but you may want to as well. You may find this program useful:

https://gist.github.com/erikh/fcf81b32fdb76bfe920a172b4a2c43b9

```go
package main

import (
	"fmt"
	"runtime"

	zfs "github.com/bicomsystems/go-libzfs"
)

func listChildren(datasets []zfs.Dataset, start []string) ([]string, error) {
	if start == nil {
		start = []string{}
	}

	for _, ds := range datasets {
		path, err := ds.Path()
		if err != nil {
			return nil, err
		}

		start = append(start, path)

		start, err = listChildren(ds.Children, start)
		if err != nil {
			return nil, err
		}

		ds.Close()
	}

	return start, nil
}

func main() {
	for i := 0; i < 1000000; i++ {
		ms := runtime.MemStats{}
		runtime.ReadMemStats(&ms)
		fmt.Printf("%v\n", ms.Alloc)
		runtime.GC()

		datasets, err := zfs.DatasetOpenAll()
		if err != nil {
			panic(err)
		}

		listChildren(datasets, nil)
	}
}
```

### CODE REVIEW

**Comment by erikh** [comment]
Hey, I'm going to fork this for now, please let me know when this is merged, and I will repoint at your repository.

**Comment by fkasumovic** [comment]
@erikh  This is a memory leak, just not the one that can be captured by go runtime. Please check my comment on issue https://github.com/bicomsystems/go-libzfs/issues/30#issuecomment-673504138

In more details, for each child dataset linked list is allocated by the implementation part written in C by calling create_dataset_list_item(). By not closing children dataset these lists are never released from memory until program calling go-libzfs exits. It might be a small leak, but it can build up over time.

**Comment by erikh** [comment]
so, the concern I have here is that the code above:

1. iterates the list of datasets
1. lists its path
1. finds the children of each dataset
1. lists the children (recursively, see below)
1. closes the dataset

I'm pretty sure no copies are being created here -- but I could be wrong.

Step 4 is where this happens. After the children are closed, then the outer dataset is closed and even though there should be no copies (note, no methods are called) the program still crashes trying to close child datasets.

I think the core issue here is that the "close" operation keeps no state about whether it was executed or not, or at least, it can't be determined whether something is already closed before attempting to close it. I don't know libzfs so I can't really say one way or another, but if you agree this is an issue I might be able to hunt it down.

**Comment by erikh** [comment]
and fwiw, I don't know if there's a leak in this code with my patches, largely because it closes things in the proper way before it ever comes back to go-libzfs for reaping. I measured numerous times with various system-level tools to determine if it was.

Entirely possible it leaks if you don't clean up like I was above, though, and I could see why you would prefer to not merge it.

**Comment by fkasumovic** [comment]
@erikh It was the only way I could reproduce the same crash. And you are right about the  "no leak" in your example because in the above example recursion handles it (way it's implemented). Maybe Close should be implemented with recursion like above, close children than parents?
But in general for each zfs.Dataset there is malloc call at zfs.c:16, it would cause memory leaks in different "use cases".

**Comment by erikh** [comment]
On Tue Aug 18, 2020 at 8:15 PM PDT, Faruk Kasumovic wrote:
> @erikh It was the only way I could reproduce the same crash. And you are
> right about the "no leak" in your example because in the above example
> recursion handles it (way it's implemented). Maybe Close should be
> implemented with recursion like above, close children than parents?
> But in general for each zfs.Dataset there is malloc call at zfs.c:16, it
> would cause memory leaks in different "use cases".

Yeah I think we're on the same page on that front; is it possible to
come up with a solution where this code does not crash? I'm happy to dig
through a little and see if I can help; I'll look at the zfs.c before I
head to bed.

I have some code in k8zfs that works around this by keeping a free list,
more or less. If you want, I can incorporate something similar...

https://code.hollensbe.org/erikh/k8zfs/src/branch/main/pkg/zfs/zfs.go
pay special attention to the handling around pool and dataset Close()
calls. There are other helpers that might be useful too, such as an
"in_pool" transactional closure I wrote in the grpc package.

Thank you so much for being so responsive!

-Erik

**Comment by fkasumovic** [comment]
@erikh Help is welcome, and thank you as well.

I'll check more.

**Comment by erikh** [comment]
hi @fkasumovic 

I've provided a patch that seems to resolve the issue for my contrived test cases :) Can you validate it's working for you? Test code and battery below.

It does change the API, but only slightly -- it makes Dataset a pointer value. While this is a large change in practice it should be a minor refactor for most users of the API.

https://gist.github.com/erikh/1af52e131ca59a6b2140a5d7fba93321 is the latest code. This shows allocation deltas and uses the API in the latest patch. Similar code to above.

To create a testpool that exacerbates the problem, try this in your shell, pasting it out of my notes here, so it might need a touch up.

```bash
export disk=$(mktemp /tmp/disk.XXXXXXX)
truncate -s20G ${disk}
zpool create testpool ${disk}
export x=testpool; 
for i in one two three
do 
  x=$x/$i
  sudo zfs create $x
done
```

**Comment by erikh** [comment]
The reason I changed to a pointer value was that yes, you were right in #30 that copies were interfering, but not quite in the same way in this case. We now track a `closed` value that must be consistent with the list, so keeping a pointer was the easiest way to do that. It also cleaned up some things in a few spots, I feel.

Anyways hope you like the patch.

**Comment by erikh** [comment]
Spoke too soon on this; seeing regressions in my other tests. I will address this tomorrow, but have a look and let me know if you're amenable to the idea.

**Comment by erikh** [comment]
This is working now.

**Review by fkasumovic — COMMENTED** [review]
@erikh This patch will lower chance of getting into this issue by doing double close of the same dataset. However, it does change the interface for everyone already using this package and potential breaks them code.

**Comment by erikh** [comment]
I sincerely suspect with the way automatic pointer dereferencing is handled in go, that this will be less of an issue that you may be expecting it to be; and porting should literally be the act of adding a `*` in a few key areas, if necessary at all. I was able to port my own code in about 20 minutes.

**Pull request closed without merging**
